
// THIS FILE WAS AUTO-GENERATED BY IMPACT.
// DO NOT MODIFY THIS FILE!
// Write to package.impact.js instead.


// THIS FILE WAS AUTO-GENERATED BY IMPACT.
// DO NOT MODIFY THIS FILE!
// Write to package.impact.js instead.

Package.describe({
  summary:  'Impact (alpha) Semantic UI package',
  name:     'impact:theme-semantic',
  version:  '0.1.0',
});

Package.on_use(function (api, where) {
  
  api.use(['impact:impact'], ['client', 'server']);
  api.imply(['impact:impact'], ['client', 'server']);
  
  //-- IMPACT: FILES --//

  api.addFiles([
    "client/semantic.css",
    "client/semantic.js",
  ], "client");


  api.addFiles([
    "files/themes/basic/assets/fonts/icons.eot",
    "files/themes/basic/assets/fonts/icons.svg",
    "files/themes/basic/assets/fonts/icons.ttf",
    "files/themes/basic/assets/fonts/icons.woff",
    "files/themes/default/assets/fonts/icons.eot",
    "files/themes/default/assets/fonts/icons.otf",
    "files/themes/default/assets/fonts/icons.svg",
    "files/themes/default/assets/fonts/icons.ttf",
    "files/themes/default/assets/fonts/icons.woff",
    "files/themes/default/assets/images/flags.png",
  ], "client");


});
